#!/usr/bin/ruby

require 'yaml'
require_relative 'errors'
require_relative 'converters/converter'
require_relative 'converters/gcal_to_ics'
require_relative 'services/google_calendar_service'

TMP = File.join(Dir.pwd, 'tmp', 'calendars')
DIR = ENV['DIR'] || File.join(Dir.pwd, 'calendars')

CREDENTIALS = YAML.load_file('credentials.yml')
SERVICE = GoogleCalendarService.new

SEPARATED = ARGV.include?('--separated-events')
VERBOSE   = ARGV.include?('-v')

Converter.new(GcalToIcs).run!
